### ISSUE TITLE
Builds sit at "Triggered" state & never move forward

### ISSUE THREAD

**Issue by brianjking** [vassilvk/readthedocs-docker#4]
I've tried on Windows 10 & OS X running newest versions of Docker. Any ideas? Thanks!

**Comment by vassilvk** [comment]
I've seen this happen when the server has no access to the Internet.

**Comment by brianjking** [comment]
Any solution? The docker image is running on a Mac and Windows computer that are both connected online.

**Comment by vassilvk** [comment]
Sorry, I can't offer any solution without having access to the machine.
I suggest you log into the container with a bash terminal and see if you can find the readthedocs logs - maybe you'll get some information about what's going on.
